# Generated by Django 5.1.7 on 2025-08-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchname', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblregister',
            fields=[
                ('name', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static/registerpic/')),
                ('batch', models.CharField(max_length=50, null=True)),
                ('address', models.TextField(null=True)),
                ('regdate', models.DateTimeField(null=True)),
            ],
        ),
    ]
