# Generated by Django 5.1.7 on 2025-08-04 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_batch_tblregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='softwarekit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('software_info', models.TextField(null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='static/softwarethum')),
                ('download_link', models.CharField(max_length=500, null=True)),
                ('posted_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static/category')),
                ('batch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.batch')),
            ],
        ),
    ]
