# Generated by Django 5.1.7 on 2025-08-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_softwarekit_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/category/'),
        ),
        migrations.AlterField(
            model_name='softwarekit',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='static/softwarethum/'),
        ),
        migrations.AlterField(
            model_name='tblgal',
            name='picture',
            field=models.ImageField(null=True, upload_to='static/modelgallery/'),
        ),
        migrations.AlterField(
            model_name='tblteam',
            name='picture',
            field=models.ImageField(upload_to='static/modelteam/'),
        ),
    ]
