# Generated by Django 5.1.7 on 2025-08-05 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_category_picture_alter_softwarekit_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblregister',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.batch'),
        ),
    ]
