# Generated by Django 5.1.7 on 2025-08-05 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_alter_tblregister_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='AdminFiles/category/'),
        ),
        migrations.AlterField(
            model_name='softwarekit',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='AdminFiles/softwarethum/'),
        ),
        migrations.AlterField(
            model_name='tblgal',
            name='picture',
            field=models.ImageField(null=True, upload_to='AdminFiles/modelgallery/'),
        ),
        migrations.AlterField(
            model_name='tblregister',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='AdminFiles/registerpic/'),
        ),
        migrations.AlterField(
            model_name='tblteam',
            name='picture',
            field=models.ImageField(upload_to='AdminFiles/modelteam/'),
        ),
        migrations.CreateModel(
            name='mylecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('video_info', models.TextField(null=True)),
                ('vlink', models.CharField(max_length=300, null=True)),
                ('posted_date', models.DateTimeField(null=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.batch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.category')),
            ],
        ),
        migrations.CreateModel(
            name='mytask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('task_info', models.TextField(null=True)),
                ('taskfile', models.FileField(blank=True, null=True, upload_to='AdminFiles/task/')),
                ('upload_task', models.FileField(blank=True, null=True, upload_to='AdminFiles/submittedtasks')),
                ('posted_date', models.DateTimeField(null=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.batch')),
            ],
        ),
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('notes_info', models.TextField(null=True)),
                ('posted_date', models.DateTimeField(null=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.batch')),
            ],
        ),
    ]
