# Generated by Django 5.1.7 on 2025-08-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_alter_category_picture_alter_softwarekit_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/category/'),
        ),
        migrations.AlterField(
            model_name='mytask',
            name='taskfile',
            field=models.FileField(blank=True, null=True, upload_to='static/task/'),
        ),
        migrations.AlterField(
            model_name='mytask',
            name='upload_task',
            field=models.FileField(blank=True, null=True, upload_to='static/submittedtasks'),
        ),
        migrations.AlterField(
            model_name='softwarekit',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='static/softwarethum/'),
        ),
        migrations.AlterField(
            model_name='tblgal',
            name='picture',
            field=models.ImageField(null=True, upload_to='static/modelgallery/'),
        ),
        migrations.AlterField(
            model_name='tblregister',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/registerpic/'),
        ),
        migrations.AlterField(
            model_name='tblteam',
            name='picture',
            field=models.ImageField(upload_to='static/modelteam/'),
        ),
    ]
