# Generated by Django 5.1.7 on 2025-08-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_alter_category_picture_alter_mytask_taskfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='notesfile',
            field=models.FileField(blank=True, null=True, upload_to='static/notes/'),
        ),
    ]
