# Generated by Django 5.1.7 on 2025-08-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_submittedtask_remove_mytask_upload_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblregister',
            name='Whatmobile',
            field=models.IntegerField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tblregister',
            name='lname',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tblregister',
            name='midname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tblregister',
            name='mobile',
            field=models.IntegerField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tblregister',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
