# Generated by Django 5.1.7 on 2025-08-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_tblregister_whatmobile_tblregister_lname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblregister',
            name='midname',
        ),
    ]
