# Generated by Django 5.1.7 on 2025-08-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_remove_tblregister_midname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblregister',
            name='Whatmobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tblregister',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
